name: action
description:

inputs:
  host:
    description: Database ip address
    required: true
  port:
    description: Database port
    required: true
  username:
    description: Database username
    required: true
  password:
    description: Database password
    required: true
  database:
    description: Database database
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@main

    - name: Setup Node.js (NPM)
      uses: actions/setup-node@master
      with:
        node-version: "18.x"

    # - name: Use cached node_modules
    #   uses: actions/cache@master
    #   with:
    #     path: node_modules
    #     key: nodeModules-${{ hashFiles('**/yarn.lock') }}
    #     restore-keys: |
    #       nodeModules-

    - name: Install dependencies
      shell: bash
      run: npm install
      env:
        CI: true

    - name: Build Development
      shell: bash
      env:
        DB_HOST: ${{inputs.host}}
        DB_PORT: ${{inputs.port}}
        DB_USERNAME: ${{inputs.username}}
        DB_PASSWORD: ${{inputs.password}}
        DB_DATABASE: ${{inputs.database}}
      run: |
        echo "DB_HOST=$DB_HOST
        DB_PORT=$DB_PORT
        DB_USERNAME=$DB_USERNAME
        DB_PASSWORD=$DB_PASSWORD
        DB_DATABASE=$DB_DATABASE" >> .env
        npm run build

    - name: Archive Production Artifact
      uses: actions/upload-artifact@main
      with:
        name: build
        path: dist
